server:
  port: 9201
spring:
  application:
    name: biz-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.51.235:3306/cloud_alibaba?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: '010626'
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl